import type { EventDefinition } from '@april-thesis/content-schema';

const hist = (date: string, sources: string[], classification: 'historical' | 'historically_plausible' | 'fictional_composite' = 'historical') => ({
  classification,
  sourceIds: sources,
  historicalDate: date,
});

export const events: EventDefinition[] = [
  {
    id: 'opening_kronstadt_aftermath',
    title: 'Aftermath of Kronstadt',
    description: 'The guns at Kronstadt have fallen silent. Red Army units occupy the fortress. The sailors\' demands for soviet democracy, free elections, and release of political prisoners were crushed after sixteen days of fighting. In Moscow, the party leadership treats the revolt as a counter-revolutionary conspiracy — but your organizers report that many workers viewed it differently.',
    month: '1921-03',
    phase: 'briefing',
    priority: 100,
    choices: [
      { id: 'condemn', text: 'Publicly condemn Kronstadt as a White Guard plot', effects: { partyLegitimacy: 10, workerSupport: -10, revolutionaryCredibility: -15 }, narrative: 'Your statement aligns with the official line. Union contacts grow cold.' },
      { id: 'silent', text: 'Remain silent on Kronstadt', effects: { exposure: -5 }, narrative: 'You offer no public statement. The party notices your absence from the condemnations.' },
      { id: 'private_sympathy', text: 'Privately express sympathy to trusted organizers', effects: { workerSupport: 10, exposure: 10, security: -5 }, narrative: 'Word spreads through factory committees. Dzerzhinsky\'s men take note.' },
    ],
    historical: hist('1921-03', ['kronstadt-1921']),
  },
  {
    id: 'tenth_congress_final_days',
    title: 'The Tenth Congress — Final Days',
    description: 'The Tenth Party Congress convenes in Moscow. Delegates debate trade unions, the economy, and party unity. Lenin pushes the New Economic Policy. The Workers\' Opposition presents its platform — and faces condemnation.',
    month: '1921-03',
    phase: 'party_politics',
    priority: 99,
    choices: [
      { id: 'attend_openly', text: 'Attend and defend the opposition platform openly', effects: { revolutionaryCredibility: 15, exposure: 20, partyLegitimacy: -15, 'character:lenin:trust': -10 }, flags: { spoke_at_congress: true } },
      { id: 'work_floor', text: 'Lobby delegates quietly on the congress floor', effects: { politicalInfluence: 10, exposure: 5, 'character:shliapnikov:trust': 5 } },
      { id: 'delegate_kollontai', text: 'Support Kollontai\'s pamphlet distribution', effects: { workerSupport: 10, exposure: 15, 'character:kollontai:trust': 10 } },
    ],
    historical: hist('1921-03', ['tenth-congress-1921']),
  },
  {
    id: 'faction_ban_resolution',
    title: 'On Party Unity',
    description: 'The Congress adopts Lenin\'s resolution "On Party Unity." Organized factions are hereby dissolved. The Workers\' Opposition is condemned as a syndicalist and anarchist deviation. The stamp falls on the page with finality.',
    month: '1921-03',
    phase: 'party_politics',
    priority: 98,
    requireFlags: ['spoke_at_congress'],
    choices: [
      { id: 'accept', text: 'Accept the resolution publicly', effects: { partyLegitimacy: 15, exposure: -10, revolutionaryCredibility: -10 }, flags: { faction_ban_passed: true, public_compliance: true } },
      { id: 'abstain', text: 'Abstain from the vote', effects: { exposure: 5, partyLegitimacy: -5 }, flags: { faction_ban_passed: true } },
      { id: 'vote_against', text: 'Vote against the resolution', effects: { revolutionaryCredibility: 20, exposure: 25, partyLegitimacy: -25, 'character:lenin:trust': -20 }, flags: { faction_ban_passed: true, voted_against_unity: true } },
    ],
    historical: hist('1921-03', ['party-unity-resolution-1921']),
  },
  {
    id: 'faction_ban_resolution_quiet',
    title: 'On Party Unity',
    description: 'The Congress adopts Lenin\'s resolution "On Party Unity." Organized factions are hereby dissolved. The Workers\' Opposition is condemned as a syndicalist and anarchist deviation.',
    month: '1921-03',
    phase: 'party_politics',
    priority: 98,
    excludeIfFlags: ['spoke_at_congress'],
    choices: [
      { id: 'accept', text: 'Accept the resolution publicly', effects: { partyLegitimacy: 15, exposure: -10 }, flags: { faction_ban_passed: true, public_compliance: true } },
      { id: 'abstain', text: 'Abstain from the vote', effects: { exposure: 5 }, flags: { faction_ban_passed: true } },
      { id: 'vote_against', text: 'Vote against the resolution', effects: { revolutionaryCredibility: 20, exposure: 25, partyLegitimacy: -25 }, flags: { faction_ban_passed: true, voted_against_unity: true } },
    ],
    historical: hist('1921-03', ['party-unity-resolution-1921']),
  },
  {
    id: 'private_meeting',
    title: 'The Meeting Tonight',
    description: 'A dim apartment near the union offices. Shliapnikov spreads a map across the table. Kollontai\'s pamphlets are stacked in the corner. Medvedev watches the door. A telegram arrived an hour ago: "The resolution has passed. What remains of the organization must decide tonight."',
    month: '1921-03',
    phase: 'faction_management',
    priority: 97,
    requireFlags: ['faction_ban_passed'],
    choices: [
      { id: 'formal_dissolve', text: 'Formally dissolve the Workers\' Opposition', effects: { exposure: -30, partyLegitimacy: 20, organizationalCapacity: -20, workerSupport: -15 }, flags: { faction_dissolved: true, faction_response: 'formal_dissolve' } },
      { id: 'public_comply', text: 'Publicly comply while continuing informally', effects: { exposure: 5, partyLegitimacy: 10, security: -5 }, flags: { faction_response: 'public_comply_informal' } },
      { id: 'secret_org', text: 'Preserve a secret organization', effects: { exposure: 15, security: 10, organizationalCapacity: 5 }, flags: { faction_response: 'secret_organization' } },
      { id: 'open_resist', text: 'Openly resist the ban', effects: { revolutionaryCredibility: 25, exposure: 35, partyLegitimacy: -30, 'character:dzerzhinsky:fear': 20 }, flags: { faction_response: 'open_resist' } },
    ],
    historical: hist('1921-03', ['workers-opposition-1921'], 'historically_plausible'),
  },
  {
    id: 'opening_strategy_choice',
    title: 'Opening Strategy',
    description: 'The faction — or what remains of it — must choose a path forward. The map of Soviet Russia lies before you, marked with union contacts, party cells, famine zones, and the shadow of the Cheka.',
    month: '1921-03',
    phase: 'faction_management',
    priority: 96,
    requireFlags: ['faction_response'],
    choices: [
      { id: 'legal_reform', text: 'Legal Party Reform — work within party institutions', effects: { politicalInfluence: 10, partyLegitimacy: 10, exposure: -5 }, flags: { opening_strategy: 'legal_party_reform' } },
      { id: 'union_mobilization', text: 'Trade-Union Mobilization — rebuild through the unions', effects: { workerSupport: 15, 'character:tomsky:trust': 10 }, flags: { opening_strategy: 'trade_union_mobilization' } },
      { id: 'underground', text: 'Underground Preservation — clandestine networks', effects: { security: 15, exposure: 10 }, flags: { opening_strategy: 'underground_preservation' } },
      { id: 'nep_safeguards', text: 'NEP with Worker Safeguards — shape the new policy', effects: { politicalInfluence: 5, 'character:bukharin:trust': 10 }, flags: { opening_strategy: 'nep_worker_safeguards' } },
      { id: 'anti_bureaucracy', text: 'Anti-Bureaucratic Coalition — ally with democratic centralists', effects: { politicalInfluence: 10, 'character:rakovsky:trust': 10 }, flags: { opening_strategy: 'anti_bureaucratic_coalition' } },
      { id: 'regional_soviet', text: 'Regional Soviet Strategy — build power in the provinces', effects: { organizationalCapacity: 10 }, flags: { opening_strategy: 'regional_soviet_strategy' } },
    ],
    historical: hist('1921-03', ['workers-opposition-1921'], 'fictional_composite'),
  },
  {
    id: 'nep_debate_april',
    title: 'The NEP Debate',
    description: 'Lenin\'s New Economic Policy replaces grain requisitioning with a tax in kind and permits limited private trade. The party is divided. Bukharin sees a path to socialism through the market. Left communists see betrayal. Workers fear NEP traders will eclipse the proletariat.',
    month: '1921-04',
    phase: 'party_politics',
    priority: 80,
    choices: [
      { id: 'support_nep', text: 'Support NEP with demands for worker protections', effects: { partyLegitimacy: 10, revolutionaryCredibility: -5, 'character:bukharin:trust': 15, 'character:lenin:trust': 5 } },
      { id: 'oppose_nep', text: 'Oppose NEP as a retreat from socialism', effects: { revolutionaryCredibility: 15, partyLegitimacy: -10, workerSupport: 5, 'character:lenin:trust': -15 } },
      { id: 'conditional', text: 'Accept NEP temporarily while organizing worker safeguards', effects: { politicalInfluence: 5, workerSupport: 10 }, flags: { nep_conditional_support: true } },
    ],
    historical: hist('1921-04', ['nep-1921']),
  },
  {
    id: 'famine_volga_april',
    title: 'Famine on the Volga',
    description: 'Reports from the Middle Volga describe catastrophe. Drought, civil war destruction, and years of requisitioning have left millions without food. Children wander orphaned along railway lines. The state\'s relief apparatus is overwhelmed.',
    month: '1921-04',
    phase: 'briefing',
    priority: 75,
    choices: [
      { id: 'organize_relief', text: 'Organize union relief brigades', effects: { treasury: -10, publicLegitimacy: 15, workerSupport: 10, 'region:middle_volga:foodSupply': 5 } },
      { id: 'demand_state_action', text: 'Demand expanded state famine relief', effects: { politicalInfluence: 5, 'character:lenin:trust': 5, publicLegitimacy: 5 } },
      { id: 'expose_corruption', text: 'Expose local relief corruption', effects: { revolutionaryCredibility: 10, exposure: 10, 'character:dzerzhinsky:fear': 10 } },
    ],
    historical: hist('1921-04', ['famine-1921-1922']),
  },
  {
    id: 'strike_petrograd_april',
    title: 'Strikes in Petrograd',
    description: 'Metalworkers in Petrograd\'s factories have stopped work. They demand food supplies, an end to bureaucratic management, and recognition of factory committees. Zinoviev\'s Petrograd organization pressures for a swift resolution.',
    month: '1921-04',
    phase: 'regional_operations',
    priority: 70,
    choices: [
      { id: 'support_strike', text: 'Support the strike publicly', effects: { workerSupport: 20, exposure: 15, 'region:petrograd:strikeActivity': 10, 'character:zinoviev:fear': 15 } },
      { id: 'mediate', text: 'Mediate between workers and management', effects: { politicalInfluence: 10, workerSupport: 5, 'region:petrograd:strikeActivity': -10 } },
      { id: 'urge_return', text: 'Urge workers to return — the state is fragile', effects: { partyLegitimacy: 10, workerSupport: -15, 'region:petrograd:strikeActivity': -20 } },
    ],
    historical: hist('1921-04', ['petrograd-strikes-1921'], 'historically_plausible'),
  },
  {
    id: 'cheka_investigation_may',
    title: 'Cheka Investigation',
    description: 'A Cheka operative has been asking questions about "trade-union education circles" in Moscow and Petrograd. Dzerzhinsky\'s men are methodical. Someone may be talking.',
    month: '1921-05',
    phase: 'briefing',
    priority: 85,
    requireFlags: ['faction_response'],
    choices: [
      { id: 'compartmentalize', text: 'Compartmentalize cells and rotate couriers', effects: { security: 15, organizationalCapacity: -5, treasury: -5 } },
      { id: 'feed_false_info', text: 'Feed false information to suspected informants', effects: { security: 10, exposure: -5, intelligence: 5 } },
      { id: 'sacrifice_organizer', text: 'Sacrifice an exposed organizer to protect the network', effects: { exposure: -20, cadreMorale: -20, security: 10 }, flags: { sacrificed_organizer: true } },
      { id: 'negotiate', text: 'Seek a meeting with sympathetic party officials', effects: { politicalInfluence: 5, 'character:kamenev:trust': 5, exposure: -5 } },
    ],
    historical: hist('1921-05', ['cheka-1921'], 'historically_plausible'),
  },
  {
    id: 'union_congress_may',
    title: 'Trade Union Congress',
    description: 'The All-Russian Congress of Trade Unions meets. Tomsky presides, balancing party directives against worker grievances. This is your strongest institutional arena — if you can navigate the contradictions.',
    month: '1921-05',
    phase: 'party_politics',
    priority: 80,
    choices: [
      { id: 'union_resolution', text: 'Propose a resolution on worker management of industry', effects: { workerSupport: 15, exposure: 10, revolutionaryCredibility: 10, 'character:tomsky:trust': -5 } },
      { id: 'lobby_delegates', text: 'Lobby sympathetic union delegates privately', effects: { politicalInfluence: 10, 'character:tomsky:trust': 5 } },
      { id: 'stay_quiet', text: 'Stay quiet and observe', effects: { intelligence: 10, exposure: -5 } },
    ],
    historical: hist('1921-05', ['trade-union-congress-1921'], 'historically_plausible'),
  },
  {
    id: 'kollontai_pamphlet_may',
    title: 'Kollontai\'s Pamphlet',
    description: 'Alexandra Kollontai wants to publish an updated statement of the Workers\' Opposition position. The original pamphlet circulated at the Tenth Congress. Publishing now would violate the faction ban — but silence has its own cost.',
    month: '1921-05',
    phase: 'faction_management',
    priority: 75,
    choices: [
      { id: 'publish', text: 'Publish the pamphlet through underground printers', effects: { revolutionaryCredibility: 15, exposure: 20, workerSupport: 10, treasury: -5, 'character:kollontai:trust': 15 } },
      { id: 'revise', text: 'Revise it as a trade-union education document', effects: { workerSupport: 5, exposure: 5, partyLegitimacy: 5 } },
      { id: 'suppress', text: 'Convince Kollontai to hold publication', effects: { exposure: -10, 'character:kollontai:trust': -15, cadreMorale: -10 } },
    ],
    historical: hist('1921-05', ['kollontai-pamphlet-1921']),
  },
  {
    id: 'tambov_rebellion_may',
    title: 'Tambov Burning',
    description: 'The Antonov rebellion in Tambov province has not been fully suppressed. Peasant partisans control swaths of countryside. The Cheka deploys chemical weapons and hostage-taking. Your peasant organizers report sympathy for the rebels.',
    month: '1921-05',
    phase: 'briefing',
    priority: 65,
    choices: [
      { id: 'condemn_rebellion', text: 'Condemn the rebellion as kulak banditry', effects: { partyLegitimacy: 10, publicLegitimacy: -5 } },
      { id: 'demand_amnesty', text: 'Demand amnesty and land reform', effects: { revolutionaryCredibility: 10, partyLegitimacy: -10, peasantCompliance: 5 } },
      { id: 'silent', text: 'Say nothing — this is not your fight', effects: {} },
    ],
    historical: hist('1921-05', ['tambov-rebellion-1921']),
  },
  {
    id: 'factory_committee_donbas_june',
    title: 'Factory Committees in the Donbas',
    description: 'Miners and metalworkers in the Donbas are rebuilding factory committees despite party directives for one-man management. Shliapnikov urges support. The regional party boss threatens expulsion.',
    month: '1921-06',
    phase: 'regional_operations',
    priority: 70,
    choices: [
      { id: 'send_organizer', text: 'Send an organizer to support the committees', effects: { workerSupport: 10, 'region:donbas:factoryCommitteeOrganization': 15, exposure: 10, treasury: -5 } },
      { id: 'advise_caution', text: 'Advise caution — the committees should negotiate', effects: { politicalInfluence: 5, 'region:donbas:factoryCommitteeOrganization': 5 } },
      { id: 'abandon', text: 'Abandon the committees to protect the organization', effects: { exposure: -10, workerSupport: -10, cadreMorale: -10 } },
    ],
    historical: hist('1921-06', ['factory-committees-1921'], 'historically_plausible'),
  },
  {
    id: 'lenin_health_june',
    title: 'Lenin\'s Exhaustion',
    description: 'Lenin has withdrawn to Gorki for rest. His absence from daily politics is noticeable. Kamenev and Zinoviev manage affairs. The balance of power shifts subtly.',
    month: '1921-06',
    phase: 'briefing',
    priority: 60,
    choices: [
      { id: 'appeal_lenin', text: 'Send a respectful appeal to Lenin at Gorki', effects: { 'character:lenin:trust': 10, partyLegitimacy: 5, exposure: 5 } },
      { id: 'act_without', text: 'Act without seeking Lenin\'s approval', effects: { politicalInfluence: 5, 'character:lenin:trust': -5 } },
      { id: 'observe', text: 'Observe the succession maneuvering', effects: { intelligence: 15 } },
    ],
    historical: hist('1921-06', ['lenin-health-1921'], 'historically_plausible'),
  },
  {
    id: 'party_vote_june',
    title: 'Central Committee Vote — Labor Policy',
    description: 'The Central Committee votes on labor discipline measures proposed by Trotsky. The vote is close. Your delegates can be lobbied.',
    month: '1921-06',
    phase: 'party_politics',
    priority: 85,
    choices: [
      { id: 'lobby_against', text: 'Lobby delegates to vote against militarized labor', effects: { politicalInfluence: -5, workerSupport: 10, revolutionaryCredibility: 10, 'character:trotsky:fear': 10 } },
      { id: 'lobby_compromise', text: 'Push for a compromise amendment', effects: { politicalInfluence: 10, partyLegitimacy: 5 } },
      { id: 'abstain_vote', text: 'Encourage abstention', effects: { exposure: -5, politicalInfluence: 5 } },
    ],
    historical: hist('1921-06', ['trade-union-debate-1921'], 'historically_plausible'),
  },
  {
    id: 'nep_traders_july',
    title: 'NEPmen on the Streets',
    description: 'Private traders — the "NEPmen" — are appearing in markets across Soviet Russia. They bring food and goods but also inequality and resentment. Workers watch traders prosper while rations shrink.',
    month: '1921-07',
    phase: 'briefing',
    priority: 65,
    choices: [
      { id: 'tax_traders', text: 'Campaign for heavy taxation of private traders', effects: { workerSupport: 10, revolutionaryCredibility: 5, 'character:bukharin:trust': -10 } },
      { id: 'cooperate', text: 'Cooperate with traders to supply workers', effects: { treasury: 10, urbanFoodSupply: 5, revolutionaryCredibility: -10 } },
      { id: 'expose', text: 'Expose trader corruption and party connections', effects: { exposure: 10, publicLegitimacy: 10, intelligence: 5 } },
    ],
    historical: hist('1921-07', ['nep-1921']),
  },
  {
    id: 'famine_worsens_july',
    title: 'The Famine Deepens',
    description: 'July brings no relief. Mortality in the Volga region exceeds anything since the civil war. Foreign relief organizations — ARA, JDC — begin operations. The Soviet state must accept help from capitalist governments.',
    month: '1921-07',
    phase: 'briefing',
    priority: 80,
    choices: [
      { id: 'coordinate_relief', text: 'Coordinate union volunteers with foreign relief', effects: { publicLegitimacy: 15, treasury: -10, 'region:middle_volga:famineSeverity': -10 } },
      { id: 'oppose_foreign', text: 'Oppose foreign relief as imperialist interference', effects: { revolutionaryCredibility: 10, publicLegitimacy: -10 } },
      { id: 'redirect', text: 'Redirect relief supplies to worker districts', effects: { workerSupport: 15, publicLegitimacy: -15, exposure: 10 } },
    ],
    historical: hist('1921-07', ['famine-1921-1922']),
  },
  {
    id: 'myasnikov_radical_july',
    title: 'Myasnikov\'s Manifesto',
    description: 'Gavril Myasnikov demands freedom of the press, liberation of all socialist prisoners, and new soviet elections. His Workers\' Group is more radical than your opposition. He asks for your endorsement.',
    month: '1921-07',
    phase: 'faction_management',
    priority: 70,
    choices: [
      { id: 'endorse', text: 'Endorse Myasnikov\'s demands', effects: { revolutionaryCredibility: 20, exposure: 25, partyLegitimacy: -20, 'character:myasnikov:trust': 20 } },
      { id: 'distance', text: 'Publicly distance from Myasnikov', effects: { partyLegitimacy: 10, 'character:myasnikov:trust': -20, workerSupport: -5 } },
      { id: 'quiet_support', text: 'Offer quiet support without public endorsement', effects: { 'character:myasnikov:trust': 10, exposure: 10 } },
    ],
    historical: hist('1921-07', ['myasnikov-1921'], 'historically_plausible'),
  },
  {
    id: 'security_raid_july',
    title: 'Security Raid',
    description: 'The Cheka raids a printing house in Moscow. Type seized. Two organizers arrested. The network is compromised — but how badly?',
    month: '1921-07',
    phase: 'consequences',
    priority: 90,
    requireFlags: ['faction_response'],
    choices: [
      { id: 'evacuate', text: 'Evacuate all connected safe houses', effects: { security: 10, organizationalCapacity: -10, treasury: -10 } },
      { id: 'legal_defense', text: 'Organize legal defense through party contacts', effects: { politicalInfluence: -5, partyLegitimacy: 5, 'character:kamenev:trust': 5 } },
      { id: 'abandon_arrested', text: 'Cut contact with arrested organizers', effects: { exposure: -15, cadreMorale: -25, security: 5 } },
    ],
    historical: hist('1921-07', ['cheka-1921'], 'historically_plausible'),
  },
  {
    id: 'internal_conference_august',
    title: 'Internal Conference',
    description: 'Six months after the ban. Your faction — or network — gathers for an internal assessment. Morale is mixed. The NEP stabilizes the economy but betrays revolutionary promises. Exposure grows or fades depending on your choices.',
    month: '1921-08',
    phase: 'faction_management',
    priority: 85,
    choices: [
      { id: 'hold_open', text: 'Hold an open debate on the faction\'s future', effects: { internalCohesion: 10, cadreMorale: 10, exposure: 10 } },
      { id: 'centralize', text: 'Centralize leadership under a tight executive', effects: { organizationalCapacity: 10, internalCohesion: -5, exposure: -5 } },
      { id: 'rewrite_program', text: 'Rewrite the political program for new conditions', effects: { revolutionaryCredibility: 10, politicalInfluence: 5, cadreMorale: 5 } },
      { id: 'dissolve_cells', text: 'Dissolve most cells and maintain only essential contacts', effects: { exposure: -20, organizationalCapacity: -15, workerSupport: -10 } },
    ],
    historical: hist('1921-08', ['workers-opposition-1921'], 'fictional_composite'),
  },
  {
    id: 'august_assessment',
    title: 'Six Months After',
    description: 'August 1921. The civil war is over but the revolution\'s meaning is contested. Your choices have shaped the Workers\' Opposition\'s survival — or its transformation into something else entirely.',
    month: '1921-08',
    phase: 'consequences',
    priority: 100,
    choices: [
      { id: 'continue', text: 'Continue the struggle into the autumn', effects: {}, flags: { chapter_one_complete: true } },
    ],
    historical: hist('1921-08', ['workers-opposition-1921'], 'fictional_composite'),
  },
  {
    id: 'shliapnikov_meeting_march',
    title: 'Shliapnikov\'s Report',
    description: 'Alexander Shliapnikov arrives with reports from metalworker delegates. The Tenth Congress votes are being counted. He believes there are more sympathizers than the leadership admits.',
    month: '1921-03',
    phase: 'faction_management',
    priority: 50,
    choices: [
      { id: 'trust', text: 'Trust his assessment and prepare for a fight', effects: { cadreMorale: 10, 'character:shliapnikov:trust': 10 } },
      { id: 'skeptical', text: 'Be skeptical — hope is not a strategy', effects: { intelligence: 5, 'character:shliapnikov:trust': -5 } },
    ],
    historical: hist('1921-03', ['shliapnikov-1921']),
  },
  {
    id: 'krupskaya_letter_april',
    title: 'A Letter from Krupskaya',
    description: 'Nadezhda Krupskaya sends a private letter expressing concern about party bureaucratization. She will not join the opposition but shares some of your criticisms.',
    month: '1921-04',
    phase: 'briefing',
    priority: 40,
    choices: [
      { id: 'reply_warmly', text: 'Reply warmly and share your analysis', effects: { 'character:krupskaya:trust': 15, intelligence: 5, exposure: 5 } },
      { id: 'reply_cautious', text: 'Reply cautiously without revealing organization', effects: { 'character:krupskaya:trust': 5 } },
      { id: 'no_reply', text: 'Do not reply — too risky', effects: {} },
    ],
    historical: hist('1921-04', ['krupskaya-1921'], 'historically_plausible'),
  },
  {
    id: 'propaganda_theme_monthly',
    title: 'Propaganda Theme',
    description: 'Choose this month\'s central propaganda message for organizers and publications.',
    month: '1921-04',
    phase: 'faction_management',
    priority: 30,
    choices: [
      { id: 'worker_control', text: 'All Power to the Organized Workers', effects: { workerSupport: 10, revolutionaryCredibility: 5, exposure: 5 } },
      { id: 'anti_bureaucracy', text: 'Save the Revolution from Bureaucracy', effects: { revolutionaryCredibility: 10, partyLegitimacy: -5 } },
      { id: 'unity', text: 'Unity Without Silence', effects: { partyLegitimacy: 5, workerSupport: -5 } },
      { id: 'bread', text: 'Bread, Production, and Workers\' Control', effects: { workerSupport: 5, publicLegitimacy: 5 } },
      { id: 'nep_serve', text: 'The NEP Must Serve Socialism', effects: { politicalInfluence: 5, revolutionaryCredibility: -5 } },
    ],
    historical: hist('1921-04', ['workers-opposition-1921'], 'fictional_composite'),
  },
  {
    id: 'organizer_assignment',
    title: 'Organizer Assignments',
    description: 'Assign your available organizers to key regions and tasks for this month.',
    month: '1921-04',
    phase: 'faction_management',
    priority: 25,
    choices: [
      { id: 'petrograd', text: 'Focus on Petrograd union networks', effects: { 'region:petrograd:workerSupport': 5, organizationalCapacity: -3 } },
      { id: 'donbas', text: 'Focus on Donbas industrial organizers', effects: { 'region:donbas:workerSupport': 5, organizationalCapacity: -3 } },
      { id: 'volga', text: 'Focus on Volga famine relief', effects: { 'region:middle_volga:foodSupply': 3, publicLegitimacy: 5, organizationalCapacity: -3 } },
      { id: 'moscow', text: 'Focus on Moscow party contacts', effects: { politicalInfluence: 5, organizationalCapacity: -3 } },
    ],
    historical: hist('1921-04', ['workers-opposition-1921'], 'fictional_composite'),
  },
];
