import type { OperationDefinition, EndingDefinition, PublicationDefinition } from '@april-thesis/content-schema';

const hist = (sources: string[]) => ({
  classification: 'historical' as const,
  sourceIds: sources,
  historicalDate: '1921-03',
});

export const operations: OperationDefinition[] = [
  { id: 'establish_union_committee', name: 'Establish Union Committee', description: 'Organize a new trade-union committee in the region', duration: 2, cost: { treasury: 5, organizationalCapacity: 3 }, effects: { 'region:TARGET:tradeUnionOrganization': 10, workerSupport: 3 }, risks: { exposureIncrease: 3 }, historical: hist(['trade-union-1921']) },
  { id: 'rebuild_factory_committee', name: 'Rebuild Factory Committee', description: 'Restore a weakened factory committee', duration: 2, cost: { treasury: 5 }, effects: { 'region:TARGET:factoryCommitteeOrganization': 12, 'region:TARGET:workerSupport': 5 }, risks: { exposureIncrease: 5 }, historical: hist(['factory-committees-1921']) },
  { id: 'send_organizer', name: 'Send Organizer', description: 'Deploy an experienced organizer to the region', duration: 1, cost: { organizationalCapacity: 5, treasury: 3 }, effects: { 'region:TARGET:influence.workersOpposition': 5, 'region:TARGET:workerSupport': 3 }, historical: hist(['workers-opposition-1921']) },
  { id: 'print_legal_newspaper', name: 'Print Legal Newspaper', description: 'Publish a legal trade-union newspaper', duration: 2, cost: { treasury: 8 }, effects: { 'region:TARGET:workerSupport': 5, publicLegitimacy: 3, politicalInfluence: 2 }, historical: hist(['press-1921']) },
  { id: 'print_illegal_circular', name: 'Print Illegal Circular', description: 'Distribute underground opposition literature', duration: 1, cost: { treasury: 5, security: 3 }, effects: { 'region:TARGET:influence.workersOpposition': 8, revolutionaryCredibility: 5 }, risks: { exposureIncrease: 8, arrestChance: 0.1 }, historical: hist(['workers-opposition-1921']) },
  { id: 'recruit_railway_workers', name: 'Recruit Railway Workers', description: 'Build contacts among railway worker unions', duration: 2, cost: { treasury: 5, organizationalCapacity: 3 }, effects: { workerSupport: 5, intelligence: 5 }, historical: hist(['railway-unions-1921']) },
  { id: 'support_strike', name: 'Support a Strike', description: 'Provide material and organizational support to strikers', duration: 1, cost: { treasury: 8, workerSupport: 3 }, effects: { 'region:TARGET:strikeActivity': 10, 'region:TARGET:workerSupport': 8 }, risks: { exposureIncrease: 10 }, historical: hist(['strikes-1921']) },
  { id: 'mediate_strike', name: 'Mediate a Strike', description: 'Negotiate between workers and management', duration: 2, cost: { organizationalCapacity: 5 }, effects: { 'region:TARGET:strikeActivity': -15, politicalInfluence: 5, partyLegitimacy: 3 }, historical: hist(['strikes-1921']) },
  { id: 'famine_relief', name: 'Support Famine Relief', description: 'Organize worker brigades for famine relief', duration: 2, cost: { treasury: 10, organizationalCapacity: 5 }, effects: { 'region:TARGET:foodSupply': 8, 'region:TARGET:famineSeverity': -5, publicLegitimacy: 8 }, historical: hist(['famine-1921-1922']) },
  { id: 'investigate_corruption', name: 'Investigate Corruption', description: 'Gather evidence of local administrative corruption', duration: 3, cost: { organizationalCapacity: 5, treasury: 3 }, effects: { intelligence: 10, 'region:TARGET:publicUnrest': 5 }, risks: { exposureIncrease: 5 }, historical: hist(['corruption-1921']) },
  { id: 'expose_administrator', name: 'Expose Local Administrator', description: 'Publish evidence against a corrupt official', duration: 2, cost: { treasury: 5 }, effects: { revolutionaryCredibility: 8, 'region:TARGET:administrativeCapacity': -5, exposure: 8 }, risks: { exposureIncrease: 10 }, historical: hist(['corruption-1921']) },
  { id: 'infiltrate_rival', name: 'Infiltrate Rival Faction', description: 'Place sympathizers inside a rival political network', duration: 3, cost: { security: 8, treasury: 5 }, effects: { intelligence: 15 }, risks: { arrestChance: 0.15 }, historical: hist(['party-politics-1921']) },
  { id: 'protect_ally', name: 'Protect Threatened Ally', description: 'Relocate and protect a threatened organizer', duration: 1, cost: { treasury: 8, security: 5 }, effects: { cadreMorale: 10, security: -3 }, historical: hist(['workers-opposition-1921']) },
  { id: 'destroy_documents', name: 'Destroy Incriminating Documents', description: 'Burn membership lists and financial records', duration: 1, cost: { organizationalCapacity: 3 }, effects: { exposure: -15, organizationalCapacity: -5 }, historical: hist(['workers-opposition-1921']) },
  { id: 'soviet_resolution', name: 'Campaign for Soviet Resolution', description: 'Push a sympathetic resolution through a local soviet', duration: 3, cost: { politicalInfluence: 5, treasury: 5 }, effects: { 'region:TARGET:localSovietAutonomy': 8, politicalInfluence: 5 }, historical: hist(['soviet-structure-1921']) },
];

export const endings: EndingDefinition[] = [
  { id: 'ending_survival', title: 'Survival Under the Ban', description: 'The Workers\' Opposition survives as a clandestine network within the party and unions.', epilogue: 'Six months after the Tenth Congress, your organization endures — diminished but not destroyed. The faction ban remains in force, but worker connections persist. The struggle continues into an uncertain autumn.', requirements: { turnNumber: 6, exposure: 50 }, historical: hist(['workers-opposition-1921']) },
  { id: 'ending_reform', title: 'Reformist Victory', description: 'Meaningful union reforms are won within the party framework.', epilogue: 'Through careful negotiation and strategic compliance, you have won concessions on union consultation and factory committee advisory powers. The revolution\'s bureaucratic drift is slowed — not halted.', requirements: { partyLegitimacy: 50, workerSupport: 50, politicalInfluence: 45 }, historical: hist(['trade-union-debate-1921']) },
  { id: 'ending_underground', title: 'Underground Legacy', description: 'The faction is defeated publicly but preserves an influential underground network.', epilogue: 'The public organization is destroyed, but printing presses still run in basement workshops. Railway workers pass messages. The revolution\'s conscience survives in whispers.', requirements: { exposure: 80, security: 50, organizationalCapacity: 30 }, historical: hist(['workers-opposition-1921']) },
  { id: 'ending_purge', title: 'The Purge', description: 'High exposure leads to arrests and organizational destruction.', epilogue: 'The Cheka came at dawn. Organizers were arrested, documents seized, printing presses smashed. The Workers\' Opposition is no more — its leaders in prison or exile.', requirements: { exposure: 95 }, historical: hist(['cheka-1921']) },
  { id: 'ending_collapse', title: 'Organizational Collapse', description: 'Loss of worker support and capacity destroys the faction.', epilogue: 'Without worker support, without organizers, without hope — the opposition dissolves not by decree but by irrelevance. The bureaucracy wins by default.', requirements: { workerSupport: 10, organizationalCapacity: 15 }, historical: hist(['workers-opposition-1921']) },
  { id: 'ending_union_power', title: 'Union Republic', description: 'Trade unions gain primary economic authority.', epilogue: 'Against all odds, the unions have become the dominant economic institution. Factory committees govern production. The party apparatus must adapt or fracture.', requirements: { workerSupport: 70, revolutionaryCredibility: 60, 'flag:opening_strategy': 'trade_union_mobilization' }, historical: hist(['workers-opposition-1921']) },
];

export const publications: PublicationDefinition[] = [
  { id: 'pravda', name: 'Pravda', bias: 'Official party line', reliability: 40, accessLevel: 'public', audience: 'Party members, officials', visualStyle: 'official-red' },
  { id: 'izvestia', name: 'Izvestia', bias: 'Government bulletin', reliability: 50, accessLevel: 'public', audience: 'General public', visualStyle: 'government-neutral' },
  { id: 'wo_circular', name: 'Workers\' Opposition Circular', bias: 'Factional advocacy', reliability: 55, accessLevel: 'restricted', audience: 'Union militants', visualStyle: 'worker-blue' },
  { id: 'regional_press', name: 'Regional Worker Press', bias: 'Local conditions', reliability: 60, accessLevel: 'public', audience: 'Local workers', visualStyle: 'regional-plain' },
  { id: 'foreign_socialist', name: 'Vorwärts (Foreign Socialist)', bias: 'International socialist', reliability: 65, accessLevel: 'restricted', audience: 'International readers', visualStyle: 'foreign-serif' },
  { id: 'cheka_digest', name: 'Cheka Internal Digest', bias: 'Security assessment', reliability: 70, accessLevel: 'classified', audience: 'Security apparatus', visualStyle: 'classified-black' },
];
