import { useMemo, useRef, useState, type KeyboardEvent, type PointerEvent, type WheelEvent } from 'react';
import type { MapMode, RegionState } from '@april-thesis/shared-types';
import { formatGameDate } from '@april-thesis/shared-types';
import { cities, geographicContext, getCityPoint, getLinePath, railways, rivers, seas } from '@april-thesis/content';
import { FACTION_COLORS, getDominantFactionAtNode, getLegendForMode, getMapModeDescription, getMapModeLabel, getRegionValueForMode, valueToColor } from '@april-thesis/map-engine';
import { audioManager } from '../audio/audioManager';
import { useGameStore } from '../store/gameStore';
import styles from './GeographicMap.module.css';

const MAP_MODES: MapMode[] = ['political_influence','formal_administration','party_organization','trade_union_strength','factory_committee_strength','local_soviet_autonomy','security_surveillance','red_army_loyalty','economic_output','food_supply','famine_disease','unrest_strikes','nationality_movements','railway_infrastructure','propaganda_reach','intelligence_confidence'];
const MIN_ZOOM=.85, MAX_ZOOM=4;

export function clampMapZoom(value:number){ return Math.max(MIN_ZOOM,Math.min(MAX_ZOOM,value)); }

export function GeographicMap(){
  const campaign=useGameStore(state=>state.campaign)!; const content=useGameStore(state=>state.content);
  const mapMode=useGameStore(state=>state.mapMode); const setMapMode=useGameStore(state=>state.setMapMode);
  const selectedRegionId=useGameStore(state=>state.selectedRegionId); const selectRegion=useGameStore(state=>state.selectRegion);
  const preferences=useGameStore(state=>state.preferences);
  const [zoom,setZoom]=useState(1); const [pan,setPan]=useState({x:0,y:0}); const [dragging,setDragging]=useState(false);
  const [layers,setLayers]=useState({influence:true,cities:true,railways:true,borders:true,uncertainty:true,operations:true});
  const [opacity,setOpacity]=useState(.72); const dragOrigin=useRef<{x:number;y:number;panX:number;panY:number}|null>(null);
  const values=Object.values(campaign.regions).map(region=>getRegionValueForMode(region,mapMode)); const min=Math.min(...values), max=Math.max(...values);
  const legend=getLegendForMode(mapMode,campaign.regions); const selectedGeometry=content.mapGeometries.find(item=>item.id===selectedRegionId);
  const neighborIds=new Set(selectedGeometry?.neighborIds??[]);
  const visibleCities=useMemo(()=>cities.filter(city=>zoom>=2.15 || city.labelPriority===1 || (zoom>=1.35&&city.labelPriority<=2)),[zoom]);

  const fillFor=(region:RegionState)=>{ if(mapMode==='political_influence'){const dominant=getDominantFactionAtNode(region); const sorted=Object.values(region.influence).sort((a,b)=>b-a); if(sorted[0]-sorted[1]<12||preferences.colorblindMode)return `url(#${dominant}-pattern)`; return FACTION_COLORS[dominant]??'#666';} return valueToColor(getRegionValueForMode(region,mapMode),min,max); };
  const changeZoom=(next:number,anchor={x:500,y:280})=>{const clamped=clampMapZoom(next); const ratio=clamped/zoom; setPan(current=>({x:anchor.x-(anchor.x-current.x)*ratio,y:anchor.y-(anchor.y-current.y)*ratio}));setZoom(clamped);};
  const reset=()=>{setZoom(1);setPan({x:0,y:0});};
  const fitSelected=()=>{if(!selectedGeometry)return;const target=2.45;setZoom(target);setPan({x:500-selectedGeometry.centerX*target,y:280-selectedGeometry.centerY*target});};
  const chooseRegion=(id:string)=>{selectRegion(id);audioManager.play('mapSelect');const geometry=content.mapGeometries.find(item=>item.id===id);if(geometry){const target=Math.max(zoom,1.65);setZoom(target);setPan({x:500-geometry.centerX*target,y:280-geometry.centerY*target});}};
  const onWheel=(event:WheelEvent<HTMLDivElement>)=>{event.preventDefault();const rect=event.currentTarget.getBoundingClientRect();changeZoom(zoom*(event.deltaY<0?1.12:.89),{x:((event.clientX-rect.left)/rect.width)*1000,y:((event.clientY-rect.top)/rect.height)*560});};
  const onPointerDown=(event:PointerEvent<SVGSVGElement>)=>{if(event.button!==0)return;event.currentTarget.setPointerCapture(event.pointerId);setDragging(true);dragOrigin.current={x:event.clientX,y:event.clientY,panX:pan.x,panY:pan.y};};
  const onPointerMove=(event:PointerEvent<SVGSVGElement>)=>{const origin=dragOrigin.current;if(!origin)return;const rect=event.currentTarget.getBoundingClientRect();setPan({x:origin.panX+(event.clientX-origin.x)*(1000/rect.width),y:origin.panY+(event.clientY-origin.y)*(560/rect.height)});};
  const endDrag=()=>{setDragging(false);dragOrigin.current=null;};
  const keyboardSelect=(event:KeyboardEvent<SVGPathElement>,id:string)=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();chooseRegion(id);}};
  const setLayer=(key:keyof typeof layers,value:boolean)=>setLayers(current=>({...current,[key]:value}));

  return <section className={styles.mapStage} aria-label="Geographic strategic map">
    <div className={styles.toolbar}><div><strong>{getMapModeLabel(mapMode)}</strong><span>{getMapModeDescription(mapMode)}</span></div><div className={styles.mapActions}><button data-testid="zoom-out" aria-label="Zoom out map" onClick={()=>changeZoom(zoom/1.25)}>−</button><output aria-label="Map zoom">{Math.round(zoom*100)}%</output><button data-testid="zoom-in" aria-label="Zoom in map" onClick={()=>changeZoom(zoom*1.25)}>+</button><button data-testid="reset-map" onClick={reset}>Reset</button><button data-testid="fit-region" disabled={!selectedGeometry} onClick={fitSelected}>Fit region</button><select aria-label="Focus strategic region" value={selectedRegionId??''} onChange={event=>event.target.value?chooseRegion(event.target.value):selectRegion(null)}><option value="">National view</option>{content.regions.map(region=><option value={region.id} key={region.id}>{region.name}</option>)}</select><select aria-label="Map mode" value={mapMode} onChange={event=>setMapMode(event.target.value as MapMode)}>{MAP_MODES.map(mode=><option key={mode} value={mode}>{getMapModeLabel(mode)}</option>)}</select></div></div>
    <div className={styles.layerBar}><label><input data-testid="toggle-influence" type="checkbox" checked={layers.influence} onChange={event=>setLayer('influence',event.target.checked)}/> political overlay</label><label><input type="checkbox" checked={layers.cities} onChange={event=>setLayer('cities',event.target.checked)}/> city labels</label><label><input data-testid="toggle-railways" type="checkbox" checked={layers.railways} onChange={event=>setLayer('railways',event.target.checked)}/> railways</label><label><input type="checkbox" checked={layers.borders} onChange={event=>setLayer('borders',event.target.checked)}/> borders</label><label><input type="checkbox" checked={layers.uncertainty} onChange={event=>setLayer('uncertainty',event.target.checked)}/> uncertainty</label><label><input type="checkbox" checked={layers.operations} onChange={event=>setLayer('operations',event.target.checked)}/> operations</label><label>opacity <input aria-label="Influence opacity" type="range" min="0.15" max="1" step="0.05" value={opacity} onChange={event=>setOpacity(Number(event.target.value))}/></label></div>
    <div className={styles.mapFrame} onWheel={onWheel} data-testid="geographic-map">
      <svg viewBox="0 0 1000 560" className={styles.map} role="group" aria-label={`${getMapModeLabel(mapMode)} geographic map of Soviet Russia and adjacent territories`} onPointerDown={onPointerDown} onPointerMove={onPointerMove} onPointerUp={endDrag} onPointerCancel={endDrag} onKeyDown={event=>{if(event.key==='+')changeZoom(zoom*1.25);if(event.key==='-')changeZoom(zoom/1.25);if(event.key==='0')reset();}}>
        <defs>{Object.entries(FACTION_COLORS).map(([faction,color])=><pattern key={faction} id={`${faction}-pattern`} patternUnits="userSpaceOnUse" width="8" height="8" patternTransform="rotate(35)"><rect width="8" height="8" fill={color}/><line y2="8" stroke="#f5e6d3" strokeOpacity=".5" strokeWidth="2"/></pattern>)}<pattern id="uncertain" patternUnits="userSpaceOnUse" width="10" height="10"><path d="M0 10L10 0M-2 2L2-2M8 12L12 8" stroke="#fff" strokeOpacity=".32"/></pattern><filter id="surface-blur"><feGaussianBlur stdDeviation={preferences.enhancedInfluence?'16':'7'}/></filter><clipPath id="territory-clip">{content.mapGeometries.map(geometry=><path d={geometry.path} key={geometry.id}/>)}</clipPath></defs>
        <rect width="1000" height="560" className={styles.sea}/><g data-testid="map-viewport" className={`${styles.viewport} ${dragging||!preferences.mapAnimation?styles.noTransition:''}`} style={{transform:`translate(${pan.x}px,${pan.y}px) scale(${zoom})`}}>
          <g className={styles.contextLand}>{geographicContext.map(feature=><path d={feature.path} key={feature.id} data-country={feature.name}/>)}</g>{seas.map(sea=><text key={sea.id} x={sea.x} y={sea.y} className={styles.seaLabel}>{sea.name}</text>)}
          <g className={styles.rivers}>{rivers.map(river=><path key={river.id} d={getLinePath(river)}><title>{river.name}</title></path>)}</g>
          {layers.railways&&<g className={styles.railways} data-testid="railway-layer">{railways.map(railway=><path key={railway.id} d={getLinePath(railway)}><title>{railway.name}</title></path>)}</g>}
          {mapMode==='political_influence'&&layers.influence&&<g data-testid="influence-layer" clipPath="url(#territory-clip)" opacity={opacity} className={styles.influenceSurface}>{content.regions.flatMap(def=>{const region=campaign.regions[def.id];const dominant=getDominantFactionAtNode(region);const regionCities=cities.filter(city=>city.regionId===def.id);const nodes=regionCities.length?regionCities.map(getCityPoint):[[def.centerX,def.centerY] as [number,number]];return nodes.map(([x,y],index)=><g key={`${def.id}-${index}`}><circle cx={x} cy={y} r={20+region.influence[dominant as keyof typeof region.influence]*.34} fill={FACTION_COLORS[dominant]??'#777'} filter="url(#surface-blur)"/><circle cx={x} cy={y} r={10+region.influence[dominant as keyof typeof region.influence]*.18} fill="none" stroke={FACTION_COLORS[dominant]??'#777'} strokeWidth="3" opacity=".7"/></g>);})}</g>}
          <g className={`${styles.regions} ${layers.borders?'':styles.noBorders}`}>{content.mapGeometries.map(geometry=>{const region=campaign.regions[geometry.id];if(!region)return null;const stale=region.intelligenceReliability<35||region.intelligenceAge>2;const selected=selectedRegionId===geometry.id;const neighbor=neighborIds.has(geometry.id);const dimmed=selectedRegionId&&!selected&&!neighbor;return <g key={geometry.id} className={`${selected?styles.selected:''} ${neighbor?styles.neighbor:''} ${dimmed?styles.dimmed:''}`}><path d={geometry.path} fill={fillFor(region)} fillOpacity={(mapMode==='political_influence'&&layers.influence) ? .34 : .82} className={styles.region} role="button" tabIndex={0} aria-label={`${content.regions.find(item=>item.id===geometry.id)?.name}: ${Math.round(getRegionValueForMode(region,mapMode))}`} onClick={event=>{event.stopPropagation();chooseRegion(geometry.id);}} onKeyDown={event=>keyboardSelect(event,geometry.id)}><title>{content.regions.find(item=>item.id===geometry.id)?.name}: ${Math.round(getRegionValueForMode(region,mapMode))}/100 · intelligence ${region.intelligenceReliability}%</title></path>{layers.uncertainty&&stale&&<path d={geometry.path} fill="url(#uncertain)" pointerEvents="none"/>}{(zoom>=1.25||(geometry.labelPriority??3)===1)&&<text x={geometry.labelX} y={geometry.labelY} className={styles.regionLabel}>{content.regions.find(item=>item.id===geometry.id)?.name}</text>}</g>;})}</g>
          {layers.cities&&<g className={styles.cities} data-testid="city-layer">{visibleCities.map(city=>{const [x,y]=getCityPoint(city);const radius=city.populationCategory==='metropolis'?5:city.populationCategory==='major'?3.6:2.5;return <g key={city.id} data-city-id={city.id}><circle cx={x} cy={y} r={radius}/><text x={x+7} y={y-5}>{city.name}</text><title>{city.name}{city.modernName?` (modern ${city.modernName})`:''} · ${city.periodNote??'1921 name record'}</title></g>;})}</g>}
          {layers.operations&&<g className={styles.operationMarkers}>{campaign.activeOperations.map(operation=>{const geometry=content.mapGeometries.find(item=>item.id===operation.regionId);return geometry?<g key={operation.id} transform={`translate(${geometry.centerX} ${geometry.centerY})`}><circle r="9"/><path d="M-4 0H4M0-4V4"/><title>{operation.operationId} · {operation.turnsRemaining} turn(s)</title></g>:null;})}</g>}
        </g>
      </svg><div className={styles.compass} aria-hidden="true"><b>N</b><i/></div><div className={styles.mapNote}>Political influence is organizational reach, not sovereignty · intelligence dated {formatGameDate(campaign.currentDate)}</div>
    </div>
    <div className={styles.legend} aria-label="Map legend">{legend.map(item=><span key={item.label}><i style={{background:item.color}}/>{item.label}{mapMode==='political_influence'?'':` ${Math.round(item.min)}–${Math.round(item.max)}`}</span>)}<span><i className={styles.hatch}/>contested / uncertain</span></div>
    <p className="sr-only">Interactive map at {Math.round(zoom*100)} percent zoom. City, railway, political overlay, administrative border, uncertainty, and operation layers are independently controllable. Use plus, minus, reset, and fit-region buttons without a mouse.</p>
  </section>;
}
