import type { CampaignHistorySnapshot, CampaignState } from '@april-thesis/shared-types';
import { formatGameDate } from '@april-thesis/shared-types';
import { deriveNationalChartSeries } from '@april-thesis/simulation';
import styles from './PoliticalCharts.module.css';

const SERIES=[['industrialProduction','#d6a65a','Industrial production'],['foodSupply','#6c9f87','Food supply'],['famineSeverity','#c64a4a','Famine severity'],['regimeStability','#7796bd','Regime stability']] as const;

function points(values:number[]){if(values.length===1)return `24,${116-values[0]}`;return values.map((value,index)=>`${24+(index/(values.length-1))*332},${116-value}`).join(' ');}

export function NationalDashboard({campaign}:{campaign:CampaignState}){
  const series=deriveNationalChartSeries(campaign.historySnapshots);
  return <section className={styles.dashboard} aria-labelledby="national-chart-title"><div className={styles.chartCard}><header><div><p>Monthly visual briefing</p><h3 id="national-chart-title">National conditions timeline</h3></div><span>{series.length} snapshot{series.length===1?'':'s'} · real campaign history</span></header><svg viewBox="0 0 380 145" role="img" aria-labelledby="national-chart-title national-chart-summary"><desc id="national-chart-summary">Monthly industrial production, urban food supply, famine severity, and regime stability. Current values are {campaign.nationalStats.industrialProduction}, {campaign.nationalStats.urbanFoodSupply}, {campaign.nationalStats.famineSeverity}, and {campaign.nationalStats.regimeStability}.</desc>{[20,40,60,80,100].map(value=><g key={value}><line x1="24" x2="356" y1={116-value} y2={116-value}/><text x="3" y={120-value}>{value}</text></g>)}{SERIES.map(([key,color,label])=><g key={key}><polyline points={points(series.map(item=>item[key]))} stroke={color}/>{series.map((item,index)=>{const list=series.map(entry=>entry[key]);const [x,y]=points(list).split(' ')[index].split(',').map(Number);return <circle key={`${item.date}-${key}`} cx={x} cy={y} r="2.7" fill={color}><title>{formatGameDate(item.date)} · {label} {item[key]}</title></circle>;})}</g>)}</svg><div className={styles.legend}>{SERIES.map(([,color,label])=><span key={label}><i style={{background:color}}/>{label}</span>)}</div><table className="sr-only"><caption>National conditions by month</caption><thead><tr><th>Month</th>{SERIES.map(([, ,label])=><th key={label}>{label}</th>)}</tr></thead><tbody>{series.map(row=><tr key={row.date}><th>{formatGameDate(row.date)}</th>{SERIES.map(([key])=><td key={key}>{row[key]}</td>)}</tr>)}</tbody></table></div><FactionProfile campaign={campaign}/><AffectedRegions history={campaign.historySnapshots}/></section>;
}

function FactionProfile({campaign}:{campaign:CampaignState}){const values=[['Worker support',campaign.resources.workerSupport,'#c64a4a'],['Party legitimacy',campaign.resources.partyLegitimacy,'#b68a4a'],['Revolutionary credibility',campaign.resources.revolutionaryCredibility,'#d66b40'],['Public legitimacy',campaign.resources.publicLegitimacy,'#6c9f87'],['Exposure',campaign.resources.exposure,'#a53a68'],['Security',campaign.resources.security,'#7796bd']] as const;return <article className={styles.profile}><header><div><p>Political profile</p><h3>Faction position</h3></div></header><div className={styles.profileBars}>{values.map(([label,value,color])=><div key={label}><span>{label}</span><b>{value}</b><i><em style={{width:`${value}%`,background:color}}/></i></div>)}</div><p className={styles.summaryText}>Exposure {campaign.resources.exposure} against security {campaign.resources.security}. Higher values are not uniformly beneficial; the profile preserves the simulation’s actual scales.</p></article>}

function AffectedRegions({history}:{history:CampaignHistorySnapshot[]}){const latest=history.at(-1);return <article className={styles.affected}><header><div><p>Current pressure</p><h3>Most affected regions</h3></div></header>{latest?.regionHighlights.map(region=><div key={region.regionId}><strong>{region.regionId.replaceAll('_',' ')}</strong><span>food {region.foodSupply} · unrest {region.unrest} · faction {region.influence}</span></div>)}</article>}

export function InstitutionalBalanceChart({campaign}:{campaign:CampaignState}){const entries=Object.values(campaign.institutions);return <section className={styles.institutionChart} aria-labelledby="institution-balance-title"><header><div><p>Formal and informal power</p><h3 id="institution-balance-title">Institutional balance</h3></div><span>line = political relationship · node = current attitude</span></header><svg viewBox="0 0 760 210" role="img" aria-labelledby="institution-balance-title"><path d="M380 45L110 110M380 45L280 110M380 45L470 110M380 45L650 110M110 110L85 178M280 110L270 178M470 110L485 178M650 110L670 178"/>{entries.slice(0,8).map((institution,index)=>{const positions=[[380,45],[110,110],[280,110],[470,110],[650,110],[85,178],[270,178],[485,178],[670,178]];const [x,y]=positions[index+1]??positions[index];const color=institution.attitude>=55?'#6c9f87':institution.attitude>=35?'#b68a4a':'#b54848';const name=institution.id.replaceAll('_',' ');return <g key={institution.id} transform={`translate(${x} ${y})`}><circle r={20+institution.factionInfluence*.12} fill={color}/><text y="3">{Math.round(institution.attitude)}</text><text y="34">{name}</text><title>{name}: attitude {Math.round(institution.attitude)}, faction influence {Math.round(institution.factionInfluence)}, contacts {institution.playerContacts}</title></g>;})}<g transform="translate(380 45)"><circle r="28" className={styles.factionNode}/><text y="3">WO</text><text y="43">Workers’ Opposition</text></g></svg><ul className="sr-only">{entries.map(institution=><li key={institution.id}>{institution.id.replaceAll('_',' ')}: attitude {Math.round(institution.attitude)}, faction influence {Math.round(institution.factionInfluence)}, contacts {institution.playerContacts}, security penetration {institution.securityPenetration}.</li>)}</ul></section>}

export function RegionalComparisonChart({campaign,regionIds}:{campaign:CampaignState;regionIds:string[]}){const metrics=[['Food','foodSupply','#6c9f87'],['Unrest','publicUnrest','#c64a4a'],['Union','tradeUnionOrganization','#d6a65a'],['Security','chekaPresence','#9b6bb0'],['Faction','influence','#b52a34']] as const;return <section className={styles.regionCompare} aria-labelledby="regional-compare-title"><h3 id="regional-compare-title">Regional comparison</h3>{regionIds.map(id=>{const region=campaign.regions[id];if(!region)return null;return <div key={id}><strong>{id.replaceAll('_',' ')}</strong><span>{metrics.map(([label,key,color])=>{const value=key==='influence'?region.influence.workersOpposition:region[key];return <i key={label} title={`${label} ${value}`} style={{height:`${Math.max(5,value)}%`,background:color}}><em>{label.slice(0,1)}</em></i>;})}</span></div>})}</section>}

export function VoteSeatingChart({campaign}:{campaign:CampaignState}){const vote=campaign.voteState;if(!vote)return null;const delegates=vote.delegates;return <section className={styles.voteChart} aria-labelledby="vote-chart-title"><header><div><p>Central Committee composite</p><h3 id="vote-chart-title">Bloc seating and commitments</h3></div><span>{vote.resolved&&vote.tally?`${vote.tally.for} for · ${vote.tally.against} against · ${vote.tally.abstain} abstain`:`${vote.declaredSupporters} likely for · ${vote.declaredOpponents} likely against · ${vote.undecided} undecided`}</span></header><svg viewBox="0 0 520 180" role="img" aria-labelledby="vote-chart-title">{delegates.map((delegate,index)=>{const row=Math.floor(index/10),col=index%10;const x=48+col*47+row*14,y=148-row*43-Math.abs(col-4.5)*2;const stance=delegate.resolvedVote??delegate.publicStance;const fill=stance==='support'||stance==='for'?'#b52a34':stance==='oppose'||stance==='against'?'#406d91':'#9a8768';return <circle key={delegate.id} cx={x} cy={y} r="12" fill={fill} className={styles.voteSeat}><title>{delegate.name} · {stance} · reliability {delegate.reliability}</title></circle>;})}<path d="M35 165Q260 15 485 165"/></svg><div className={styles.voteLegend}><span><i className={styles.support}/>support</span><span><i className={styles.oppose}/>oppose</span><span><i className={styles.undecided}/>undecided / abstain</span></div></section>}
